version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test DialogFlow.Sdk.Tests/DialogFlow.Sdk.Tests.cspro