version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test DialogFlow.Sdk.Tests/DialogFlow.Sdk.Tests.csproj --no-build --logger:nunit
      - run: dotnet test Jobber.SmartAssistant.Tests/Jobber.SmartAssistant.Tests.csproj --no-build --logger:nunit
      - run:
          name: Collect test results
          command: |
            mkdir -p ~/TestResults/
            find . -type f -regex ".*TestResults.xml" -exec cp {} ~/TestResults/ \;
          when: always
      - store_test_results:
          path: ~/TestResults/
      - store_artifacts:
          path: ~/TestResults/