version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test DialogFlow.Sdk.Tests/DialogFlow.Sdk.Tests.csproj --no-build --logger:nunit
      - store_test_results:
          path: **/TestResults/*.xml